apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: aws-load-balancer-controller
rules:
  - apiGroups:
    - ""
    resources: 
      - nodes
      - services
      - endpoints
    verbs: 
      - get
      - list
      - watch
  - apiGroups:
    - networking.k8s.io
    resources:
      - ingress
      - ingress/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - "elbv2.k8s.aws"
    resources:
      - loadbalancers
      - listeners
      - targets
    verbs:
      - get
      - list
      - watch 
      - create
      - update
      - delete